// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASut5xXHrfx3gtsRbmx5PY9OxLpZDVdDM',
    appId: '1:1094168299826:web:f9683de9fbd3e9d8b3af2b',
    messagingSenderId: '1094168299826',
    projectId: 'travel-app-cgp',
    authDomain: 'travel-app-cgp.firebaseapp.com',
    storageBucket: 'travel-app-cgp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG6LzzoF9t8gwXlhGD1yXKwcmnqMGXuXM',
    appId: '1:1094168299826:android:18c47cdb63d25d92b3af2b',
    messagingSenderId: '1094168299826',
    projectId: 'travel-app-cgp',
    storageBucket: 'travel-app-cgp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1QBnxiLGCoroILVg5QCaDKBcceHm1-xs',
    appId: '1:1094168299826:ios:ce356c1dd0437f4ab3af2b',
    messagingSenderId: '1094168299826',
    projectId: 'travel-app-cgp',
    storageBucket: 'travel-app-cgp.firebasestorage.app',
    iosBundleId: 'com.example.newone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1QBnxiLGCoroILVg5QCaDKBcceHm1-xs',
    appId: '1:1094168299826:ios:ce356c1dd0437f4ab3af2b',
    messagingSenderId: '1094168299826',
    projectId: 'travel-app-cgp',
    storageBucket: 'travel-app-cgp.firebasestorage.app',
    iosBundleId: 'com.example.newone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASut5xXHrfx3gtsRbmx5PY9OxLpZDVdDM',
    appId: '1:1094168299826:web:4b6df4bf1b113a0cb3af2b',
    messagingSenderId: '1094168299826',
    projectId: 'travel-app-cgp',
    authDomain: 'travel-app-cgp.firebaseapp.com',
    storageBucket: 'travel-app-cgp.firebasestorage.app',
  );
}
